# Delay in seconds between polling for new images (default: 60)
delay = 60

[proxy]
enabled = true

[telemetry]
enabled = true
table_uri_deployments = "telem/deployments"
table_uri_status = "telem/status"
table_uri_logs = "telem/logs"
table_uri_container_output = "telem/container_out"
table_uri_traces = "telem/traces"

[[service]]
path = "service1"

[[service]]
path = "service2"

[[service]]
path = "hello-world"
