[package]
name = "dispenser"
version = "0.4.0"
edition = "2021"
license = "MIT"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.42"
clap = { version = "4.5.18", features = ["derive"] }
cron = { version = "0.15.0", features = ["serde"] }
env_logger = "0.11.5"
log = "0.4.22"
rayon = "1.11.0"
sd-notify = "0.4.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
signal-hook = "0.3.17"
toml = "0.8.19"
urlencoding = "2.1.3"
